version: '1.0'
services:
  backend:
    container_name: backend
    build: ./server/
    ports:
      - 4000:4000
  frontend:
    container_name: frontend
    build: ./client/
    ports:
      - 3000:3000